# Mitra configuration file

database_url: postgres://mitra:mitra@127.0.0.1:5432/mitra
storage_dir: /var/lib/mitra
# Path to web client static files
web_client_dir: /usr/share/mitra/www

http_host: '127.0.0.1'
http_port: 8383

# List of allowed origins for CORS (in addition to main)
#http_cors_allowlist: []

# Log level (debug, info, warn)
#log_level: info

# Domain name
instance_uri: https://example.tld

instance_title: example
instance_short_description: my instance
# Long description can contain markdown syntax
instance_description: |
  # My instance
  Welcome!

registration:
  # Possible values: open, invite
  type: invite
  # Possible values: user, read_only_user
  default_role: user

# EIP-4361 login message
#login_message: 'Do not sign this message on other sites!'

# Limits
#limits:
#  media:
#    file_size_limit: 20M
#  posts:
#    character_limit: 2000

# Data retention parameters
retention:
  extraneous_posts: 50
  empty_profiles: 150

# Federation parameters
#federation:
#  enabled: true
#  # Proxy for outgoing requests
#  #proxy_url: 'socks5h://127.0.0.1:9050'
#  # Proxy for outgoing requests to .onion targets
#  #onion_proxy_url: 'socks5h://127.0.0.1:9050'

# List of blocked domains
#blocked_instances: []

# IPFS integration
#ipfs_api_url: 'http://127.0.0.1:5001'
# IPFS gateway (for clients)
#ipfs_gateway_url: 'https://ipfs.example.tld'
