matrix:
  RUST: [stable]

pipeline:

  check-style:
    image: rust
    when:
      branch: [ master ]
      path:
        include:
          - src/**/*.rs
          - fedimovies-cli/**/*.rs
          - fedimovies-config/**/*.rs
          - fedimovies-models/**/*.rs
          - fedimovies-utils/**/*.rs
    commands:
      - rustup default $RUST
      - cargo clippy --all-targets --all-features -- -D warnings

  run-tests:
    image: rust
    when:
      branch: [ master ]
      path:
        include:
          - src/**/*.rs
          - fedimovies-cli/**/*.rs
          - fedimovies-config/**/*.rs
          - fedimovies-models/**/*.rs
          - fedimovies-utils/**/*.rs
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup default $RUST
      - cargo test --all -- --nocapture
