matrix:
  RUST: [stable]

pipeline:

  check-style:
    image: rust
    when:
      branch: [ master ]
      path:
        include:
          - "./**/*.rs"
    commands:
      - rustup default $RUST
      - cargo clippy --all-targets --all-features -- -D warnings

  run-tests:
    image: rust
    when:
      branch: [ master ]
      path:
        include:
          - "./**/*.rs"
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup default $RUST
      - cargo test --all -- --nocapture
